version: '3.8'

services:
  app:
    build: .
    container_name: koknese-api
    ports:
      - "3001:3001"
      - "9000:9000"
      - "9001:9001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - /usr/src/app/node_modules